Repository typelevel/cats, pull requests merged in 2018-12, with the labels that each got.

#2636 Some changes to glossary.
  docs/src/main/tut/nomenclature.md
Labels: documentation

#2659 change prePR to run BC test on Scala 2.11
  build.sbt
Labels: build

#2654 Add a shell.nix and instructions for using it
  CONTRIBUTING.md
  shell.nix
Labels: build, speculative
