Repository typelevel/cats, pull requests merged in 2018-11, with the labels that each got.

#2591 Update tut-plugin to 0.6.9
  project/plugins.sbt
Labels: build

#2579 Added `Chain#distinct` and `NonEmptyChain#distinct` to match `List#distinct` and `NonEmptyList#distinct`
  core/src/main/scala/cats/data/Chain.scala
  core/src/main/scala/cats/data/NonEmptyChain.scala
  tests/src/test/scala/cats/tests/ChainSuite.scala
  tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
Labels: enhancement

#2558 Add Nomenclature / Cheatsheet page
  docs/src/main/tut/nomenclature.md
Labels: documentation

#2597 Optimize `Apply` methods in `FlatMap`
  core/src/main/scala/cats/FlatMap.scala
Labels: enhancement

#2594 Get FunctorFilter on par with the other MTL typeclasses
  core/src/main/scala/cats/data/IndexedStateT.scala
  core/src/main/scala/cats/data/Kleisli.scala
  tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
  tests/src/test/scala/cats/tests/KleisliSuite.scala
Labels: enhancement

#2615 2611 - MonadError syntax for OptionT uses incorrect instance
  binCompatTest/src/main/scala/catsBC/MimaExceptions.scala
  build.sbt
  core/src/main/scala/cats/data/OptionT.scala
  tests/src/test/scala/cats/tests/OptionTSuite.scala
Labels: bug
