Repository typelevel/cats, pull requests merged in 2019-04, with the labels that each got.

#2577 Don't depend on random sampling to determine function equivalence
  free/src/test/scala/cats/free/FreeInvariantMonoidalSuite.scala
  free/src/test/scala/cats/free/FreeTSuite.scala
  laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
  laws/src/main/scala/cats/laws/discipline/Eq.scala
  laws/src/main/scala/cats/laws/discipline/ExhaustiveCheck.scala
  laws/src/main/scala/cats/laws/discipline/MiniInt.scala
  tests/src/test/scala/cats/tests/AlgebraInvariantSuite.scala
  tests/src/test/scala/cats/tests/AndThenSuite.scala
  tests/src/test/scala/cats/tests/BinCodecInvariantMonoidalSuite.scala
  tests/src/test/scala/cats/tests/BinestedSuite.scala
  tests/src/test/scala/cats/tests/CategorySuite.scala
  tests/src/test/scala/cats/tests/CokleisliSuite.scala
  tests/src/test/scala/cats/tests/ComposeSuite.scala
  tests/src/test/scala/cats/tests/ContravariantSuite.scala
  tests/src/test/scala/cats/tests/CsvCodecInvariantMonoidalSuite.scala
  tests/src/test/scala/cats/tests/EitherKSuite.scala
  tests/src/test/scala/cats/tests/EqSuite.scala
  tests/src/test/scala/cats/tests/EquivSuite.scala
  tests/src/test/scala/cats/tests/FuncSuite.scala
  tests/src/test/scala/cats/tests/FunctionSuite.scala
  tests/src/test/scala/cats/tests/IndexedReaderWriterStateTSuite.scala
  tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
  tests/src/test/scala/cats/tests/KernelContravariantSuite.scala
  tests/src/test/scala/cats/tests/KleisliSuite.scala
  tests/src/test/scala/cats/tests/MiniIntSuite.scala
  tests/src/test/scala/cats/tests/NestedSuite.scala
  tests/src/test/scala/cats/tests/OpSuite.scala
  tests/src/test/scala/cats/tests/OptionTSuite.scala
  tests/src/test/scala/cats/tests/OptionWrapper.scala
  tests/src/test/scala/cats/tests/OrderSuite.scala
  tests/src/test/scala/cats/tests/OrderingSuite.scala
  tests/src/test/scala/cats/tests/ParallelSuite.scala
  tests/src/test/scala/cats/tests/PartialOrderSuite.scala
  tests/src/test/scala/cats/tests/PartialOrderingSuite.scala
  tests/src/test/scala/cats/tests/RepresentableSuite.scala
  tests/src/test/scala/cats/tests/ShowSuite.scala
  tests/src/test/scala/cats/tests/Tuple2KSuite.scala
  tests/src/test/scala/cats/tests/WriterTSuite.scala
Labels: speculative

#2780 added `foldF` to `EitherT`
  core/src/main/scala/cats/data/EitherT.scala
  tests/src/test/scala/cats/tests/EitherTSuite.scala
Labels: enhancement

#2804 Update sbt-scala-native to 0.3.9
  project/plugins.sbt
Labels: build
