Repository typelevel/cats, pull requests merged in 2019-02, with the labels that each got.

#2722 Add more doctests to Kleisli
  core/src/main/scala/cats/data/Kleisli.scala
Labels: documentation

#2672 Alter from Reflexitivity to Reflexivity
  kernel-laws/src/main/scala/cats/kernel/laws/EqLaws.scala
  kernel-laws/src/main/scala/cats/kernel/laws/PartialOrderLaws.scala
  kernel-laws/src/main/scala/cats/kernel/laws/discipline/EqTests.scala
  kernel-laws/src/main/scala/cats/kernel/laws/discipline/PartialOrderTests.scala
Labels: Binary Breaking, Source Breaking

#2640 Strong profunctor laws based on category theory
  laws/src/main/scala/cats/laws/StrongLaws.scala
  laws/src/main/scala/cats/laws/discipline/ArrowChoiceTests.scala
  laws/src/main/scala/cats/laws/discipline/ArrowTests.scala
  laws/src/main/scala/cats/laws/discipline/CommutativeArrowTests.scala
  laws/src/main/scala/cats/laws/discipline/StrongTests.scala
Labels: Binary Breaking
