Repository typelevel/cats, pull requests merged in 2019-11, with the labels that each got.

#3103 Add TraverseFilter instance for Queue.
  core/src/main/scala/cats/instances/queue.scala
  tests/src/test/scala/cats/tests/QueueSuite.scala
Labels: enhancement

#3041 Add scala.util.control.TailCalls.TailRec instances
  bench/src/main/scala/cats/bench/TrampolineBench.scala
  core/src/main/scala-2.12/cats/instances/all.scala
  core/src/main/scala-2.12/cats/instances/package.scala
  core/src/main/scala-2.13+/cats/instances/all.scala
  core/src/main/scala-2.13+/cats/instances/package.scala
  core/src/main/scala/cats/Eval.scala
  core/src/main/scala/cats/instances/tailrec.scala
  tests/src/test/scala/cats/tests/TailRecSuite.scala
Labels: enhancement

#3062 add unzip to Functor
  core/src/main/scala/cats/Functor.scala
  tests/src/test/scala/cats/tests/FunctorSuite.scala
Labels: enhancement

#3015 Use Foldable foldRight for Traverse and TraverseFilter.
  core/src/main/scala/cats/data/Chain.scala
  core/src/main/scala/cats/instances/list.scala
Labels: enhancement

#3126 Fix #3039
  core/src/main/scala/cats/instances/sortedSet.scala
  kernel/src/main/scala/cats/kernel/instances/SortedSetInstances.scala
Labels: bug

#2834 CommutativeMonoid[Option[A]] from CommutativeSemigroup
  kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
  kernel/src/main/scala/cats/kernel/instances/OptionInstances.scala
Labels: enhancement

#3129 Check bincompat on stuff we should be checking bincompat for
  .travis.yml
  build.sbt
  core/src/main/scala-2.13+/cats/instances/stream.scala
Labels: build

#3130 change constraint for foldMapM from Monad to Applicative
  core/src/main/scala/cats/Foldable.scala
  tests/src/test/scala/cats/tests/FoldableSuite.scala
Labels: enhancement

#2772 Add foldRightDefer to Foldable
  core/src/main/scala/cats/Foldable.scala
  laws/src/main/scala/cats/laws/FoldableLaws.scala
  laws/src/main/scala/cats/laws/discipline/FoldableTests.scala
  tests/src/test/scala/cats/tests/FoldableSuite.scala
Labels: enhancement

#3144 Add Align for Stream
  core/src/main/scala-2.12/cats/instances/stream.scala
  core/src/main/scala-2.13+/cats/instances/lazyList.scala
  core/src/main/scala-2.13+/cats/instances/stream.scala
  core/src/main/scala/cats/Align.scala
  tests/src/test/scala/cats/tests/StreamSuite.scala
Labels: enhancement

#3142 Backport MiMa config and dependency updates for 2.11
  .scalafmt.conf
  build.sbt
  core/src/main/scala/cats/data/NonEmptyList.scala
  core/src/main/scala/cats/data/NonEmptyVector.scala
  core/src/main/scala/cats/instances/option.scala
  core/src/main/scala/cats/instances/parallel.scala
  core/src/main/scala/cats/instances/sortedMap.scala
  core/src/main/scala/cats/instances/sortedSet.scala
  laws/src/main/scala/cats/laws/discipline/MiniInt.scala
  project/plugins.sbt
  tests/src/test/scala/cats/tests/SemigroupSuite.scala
Labels: build

#3149 Deprecate and make private syntax methods that are now on Either
  core/src/main/scala/cats/syntax/either.scala
Labels: enhancement

#2380 Add combineAllOption to Foldable
  core/src/main/scala-2.12/cats/compat/FoldableCompat.scala
  core/src/main/scala-2.12/cats/instances/stream.scala
  core/src/main/scala-2.13+/cats/compat/FoldableCompat.scala
  core/src/main/scala-2.13+/cats/instances/lazyList.scala
  core/src/main/scala-2.13+/cats/instances/stream.scala
  core/src/main/scala/cats/Foldable.scala
  core/src/main/scala/cats/syntax/foldable.scala
  tests/src/test/scala/cats/tests/FoldableSuite.scala
Labels: enhancement

#2742 Added separateFoldable
  core/src/main/scala/cats/Alternative.scala
  core/src/main/scala/cats/syntax/alternative.scala
  tests/src/test/scala/cats/tests/AlternativeSuite.scala
  tests/src/test/scala/cats/tests/SyntaxSuite.scala
Labels: enhancement

#3146 Add redeem and redeemWith
  core/src/main/scala/cats/ApplicativeError.scala
  core/src/main/scala/cats/MonadError.scala
  core/src/main/scala/cats/instances/either.scala
  core/src/main/scala/cats/instances/future.scala
  core/src/main/scala/cats/instances/option.scala
  core/src/main/scala/cats/instances/try.scala
  core/src/main/scala/cats/syntax/applicativeError.scala
  core/src/main/scala/cats/syntax/monadError.scala
  laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
  laws/src/main/scala/cats/laws/MonadErrorLaws.scala
  laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala
  laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala
  tests/src/test/scala/cats/tests/SyntaxSuite.scala
Labels: enhancement

#3147 Add Parallel.parFoldMapA
  core/src/main/scala/cats/Parallel.scala
  core/src/main/scala/cats/syntax/all.scala
  core/src/main/scala/cats/syntax/package.scala
  core/src/main/scala/cats/syntax/parallel.scala
  tests/src/test/scala/cats/tests/ParallelSuite.scala
  tests/src/test/scala/cats/tests/SyntaxSuite.scala
Labels: enhancement

#3148 Move adaptError
  core/src/main/scala/cats/ApplicativeError.scala
  core/src/main/scala/cats/MonadError.scala
  core/src/main/scala/cats/syntax/applicativeError.scala
  laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
  laws/src/main/scala/cats/laws/MonadErrorLaws.scala
  laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala
  laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala
  tests/src/test/scala/cats/tests/SyntaxSuite.scala
Labels: enhancement

#3156 Fix link to Monad and Comonad
  docs/src/main/tut/datatypes/id.md
Labels: documentation

#3154 Make 1.x deprecation targets package-private
  core/src/main/scala/cats/Apply.scala
  core/src/main/scala/cats/FlatMap.scala
  core/src/main/scala/cats/Parallel.scala
  core/src/main/scala/cats/data/Kleisli.scala
  core/src/main/scala/cats/data/NonEmptyList.scala
  core/src/main/scala/cats/instances/duration.scala
  core/src/main/scala/cats/instances/finiteDuration.scala
  core/src/main/scala/cats/package.scala
  core/src/main/scala/cats/syntax/apply.scala
  core/src/main/scala/cats/syntax/flatMap.scala
  core/src/main/scala/cats/syntax/package.scala
  core/src/main/scala/cats/syntax/semigroupal.scala
  free/src/main/scala/cats/free/Coyoneda.scala
  free/src/main/scala/cats/free/FreeT.scala
  free/src/main/scala/cats/free/Trampoline.scala
  tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
Labels: enhancement

#3152 "Move" type class syntax methods onto type classes
  core/src/main/scala/cats/ApplicativeError.scala
  core/src/main/scala/cats/Apply.scala
  core/src/main/scala/cats/Bitraverse.scala
  core/src/main/scala/cats/FlatMap.scala
  core/src/main/scala/cats/Foldable.scala
  core/src/main/scala/cats/Reducible.scala
  core/src/main/scala/cats/TraverseFilter.scala
  core/src/main/scala/cats/UnorderedFoldable.scala
  core/src/main/scala/cats/syntax/applicativeError.scala
  core/src/main/scala/cats/syntax/apply.scala
  core/src/main/scala/cats/syntax/bitraverse.scala
  core/src/main/scala/cats/syntax/flatMap.scala
  core/src/main/scala/cats/syntax/foldable.scala
  core/src/main/scala/cats/syntax/reducible.scala
  core/src/main/scala/cats/syntax/traverseFilter.scala
  core/src/main/scala/cats/syntax/unorderedFoldable.scala
  core/src/main/scala/cats/syntax/validated.scala
Labels: enhancement

#3162 Add adaptError override to MonadError
  core/src/main/scala/cats/MonadError.scala
Labels: bug

#3166 Update Scala to 2.13.1
  .travis.yml
  CHANGES.md
  README.md
  project/plugins.sbt
Labels: build

#3163 Fix broken binary compatibility
  PULL_REQUEST_TEMPLATE.md
  kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
  kernel/src/main/scala/cats/kernel/instances/OptionInstances.scala
  kernel/src/main/scala/cats/kernel/instances/QueueInstances.scala
  kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala
  project/KernelBoiler.scala
  tests/src/test/scala/cats/tests/EqSuite.scala
  tests/src/test/scala/cats/tests/ListSuite.scala
  tests/src/test/scala/cats/tests/QueueSuite.scala
  tests/src/test/scala/cats/tests/VectorSuite.scala
Labels: bug

#3167 Make default reduceMapM lazy if reduceRightTo is lazy
  core/src/main/scala/cats/Reducible.scala
  tests/src/test/scala/cats/tests/ReducibleSuite.scala
Labels: enhancement

#3159 Some minor optimizations
  bench/src/main/scala/cats/bench/ParTraverseBench.scala
  bench/src/main/scala/cats/bench/ValidatedBench.scala
  core/src/main/scala/cats/Parallel.scala
  core/src/main/scala/cats/data/Cokleisli.scala
  core/src/main/scala/cats/data/EitherT.scala
  core/src/main/scala/cats/data/Func.scala
  core/src/main/scala/cats/data/IdT.scala
  core/src/main/scala/cats/data/IorT.scala
  core/src/main/scala/cats/data/Kleisli.scala
  core/src/main/scala/cats/data/Nested.scala
  core/src/main/scala/cats/data/NonEmptyChain.scala
  core/src/main/scala/cats/data/NonEmptyList.scala
  core/src/main/scala/cats/data/NonEmptySet.scala
  core/src/main/scala/cats/data/Validated.scala
Labels: enhancement

#3165 Add catchOnly to ApplicativeError.
  core/src/main/scala/cats/ApplicativeError.scala
  core/src/main/scala/cats/instances/try.scala
  tests/src/test/scala/cats/tests/TrySuite.scala
Labels: enhancement
