Repository typelevel/cats, pull requests merged in 2019-05, with the labels that each got.

#2796 Added collectFirst to Chain and NonEmptyChain
  core/src/main/scala/cats/data/Chain.scala
  core/src/main/scala/cats/data/NonEmptyChain.scala
Labels: enhancement

#2827 In Apply.semigroup test replace ` ListWrapper` with `Option`
  core/src/main/scala/cats/Apply.scala
  tests/src/test/scala/cats/tests/ApplicativeSuite.scala
Labels: testing

#2817 added a new foldRight lazy law, move forallLazy and existLazy laws
  core/src/main/scala/cats/UnorderedFoldable.scala
  core/src/main/scala/cats/data/NonEmptyChain.scala
  core/src/main/scala/cats/instances/map.scala
  core/src/main/scala/cats/instances/set.scala
  laws/src/main/scala/cats/laws/FoldableLaws.scala
  laws/src/main/scala/cats/laws/UnorderedFoldableLaws.scala
  laws/src/main/scala/cats/laws/discipline/FoldableTests.scala
  laws/src/main/scala/cats/laws/discipline/UnorderedFoldableTests.scala
  tests/src/test/scala/cats/tests/UnorderedFoldableSuite.scala
Labels: bug

#2831 fixed applicative monoid test
  tests/src/test/scala/cats/tests/ApplicativeSuite.scala
Labels: testing

#2830 remove deprecated eq instances from scope
  laws/src/main/scala/cats/laws/discipline/Eq.scala
Labels: testing

#2843 Kleisli contravariant on input type A
  core/src/main/scala/cats/data/Kleisli.scala
  tests/src/test/scala/cats/tests/KleisliSuite.scala
Labels: Source Breaking, enhancement
