Repository typelevel/cats, pull requests merged in 2019-01, with the labels that each got.

#2655 Add `rethrowT` method to EitherT
  core/src/main/scala/cats/data/EitherT.scala
  core/src/main/scala/cats/syntax/monadError.scala
  tests/src/test/scala/cats/tests/EitherTSuite.scala
  tests/src/test/scala/cats/tests/MonadErrorSuite.scala
Labels: enhancement

#2690 Override equals and hashCode on Chain
  core/src/main/scala/cats/data/Chain.scala
  testkit/src/main/scala/cats/tests/ListWrapper.scala
  tests/src/test/scala/cats/tests/ChainSuite.scala
Labels: enhancement

#2670 Issue 2657 - Ambiguous duration instances
  core/src/main/scala/cats/implicits.scala
  core/src/main/scala/cats/instances/all.scala
  core/src/main/scala/cats/instances/duration.scala
  core/src/main/scala/cats/instances/finiteDuration.scala
  core/src/main/scala/cats/instances/package.scala
  testkit/src/main/scala/cats/tests/CatsSuite.scala
  tests/src/test/scala/cats/tests/ShowSuite.scala
Labels: bug

#2693 Add IndexedState alias (#2686)
  core/src/main/scala/cats/data/IndexedStateT.scala
  core/src/main/scala/cats/data/package.scala
Labels: enhancement

#2609 Add an If-Then-Else operation to the Apply.
  core/src/main/scala/cats/syntax/all.scala
  core/src/main/scala/cats/syntax/apply.scala
Labels: enhancement

#2574 Remove duplicate menu item in docs
  docs/src/main/resources/microsite/data/menu.yml
Labels: documentation

#2692 Private val in value classes (Resolve TODO since 2.10 is dropped)
  binCompatTest/src/main/scala/catsBC/MimaExceptions.scala
  build.sbt
  core/src/main/scala/cats/syntax/either.scala
  core/src/main/scala/cats/syntax/foldable.scala
  core/src/main/scala/cats/syntax/reducible.scala
  core/src/main/scala/cats/syntax/traverseFilter.scala
  kernel-laws/src/main/scala/cats/kernel/laws/package.scala
  laws/src/main/scala/cats/laws/package.scala
  project/Boilerplate.scala
  project/KernelBoiler.scala
Labels: bug
