Repository typelevel/cats, pull requests merged in 2019-07, with the labels that each got.

#2828 make stage more explicit
  .travis.yml
Labels: build

#2942 fix Cofree.cata stack-safety #2940
  free/src/main/scala/cats/free/Cofree.scala
  free/src/test/scala/cats/free/CofreeSuite.scala
Labels: bug

#2941 Added `NonEmptyLazyList` to replace `NonEmptyStream`
  core/src/main/scala-2.12-/cats/data/ScalaVersionSpecificPackage.scala
  core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
  core/src/main/scala-2.13+/cats/data/ScalaVersionSpecificPackage.scala
  core/src/main/scala/cats/data/AbstractNonEmptyInstances.scala
  core/src/main/scala/cats/data/Newtype.scala
  core/src/main/scala/cats/data/NonEmptyChain.scala
  core/src/main/scala/cats/data/NonEmptyList.scala
  core/src/main/scala/cats/data/NonEmptyMapImpl.scala
  core/src/main/scala/cats/data/NonEmptySet.scala
  core/src/main/scala/cats/data/NonEmptyVector.scala
  core/src/main/scala/cats/data/package.scala
  kernel/src/main/scala-2.13+/cats/kernel/compat/scalaVersionMoreSpecific.scala
  kernel/src/main/scala/cats/kernel/instances/StreamInstances.scala
  laws/src/main/scala-2.12-/cats/laws/discipline/ScalaVersionSpecific.scala
  laws/src/main/scala-2.13+/cats/laws/discipline/ScalaVersionSpecific.scala
  laws/src/main/scala/cats/laws/discipline/arbitrary.scala
  tests/src/test/scala-2.12-/cats/tests/NonEmptyStreamSuite.scala
  tests/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
  tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
  tests/src/test/scala/cats/tests/OneAndSuite.scala
  tests/src/test/scala/cats/tests/ParallelSuite.scala
Labels: enhancement

#2939 add map to NonEmptyChain.
  core/src/main/scala/cats/data/NonEmptyChain.scala
Labels: enhancement
