Repository typelevel/cats, pull requests merged in 2020-02, with the labels that each got.

#3302 ArraySeq instance follow-up
  core/src/main/scala-2.13+/cats/instances/arraySeq.scala
  kernel/src/main/scala-2.13+/cats/kernel/instances/ArraySeqInstances.scala
  tests/src/test/scala-2.13+/cats/tests/ArraySeqSuite.scala
Labels: enhancement

#3305 Add cats.syntax.hash
  core/src/main/scala/cats/syntax/package.scala
Labels: enhancement

#3306 Make cats.syntax.flatMap include untilDefinedM
  core/src/main/scala/cats/syntax/package.scala
Labels: enhancement

#3314 Fix doc examples for Ior.map
  core/src/main/scala/cats/data/Ior.scala
Labels: documentation

#3311 Update sbt-microsites to 1.1.2
  project/plugins.sbt
Labels: build

#3303 Use unlimited MathContext for BigDecimal arithmetic
  kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
  kernel/src/main/scala/cats/kernel/instances/BigDecimalInstances.scala
Labels: enhancement

#3279 Add Semigroup and Monoid combinators reverse and intercalate
  core/src/main/scala/cats/Foldable.scala
  core/src/main/scala/cats/Reducible.scala
  kernel-laws/shared/src/main/scala/cats/kernel/laws/SemigroupLaws.scala
  kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/SemigroupTests.scala
  kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
  kernel/src/main/scala/cats/kernel/Band.scala
  kernel/src/main/scala/cats/kernel/BoundedSemilattice.scala
  kernel/src/main/scala/cats/kernel/CommutativeMonoid.scala
  kernel/src/main/scala/cats/kernel/CommutativeSemigroup.scala
  kernel/src/main/scala/cats/kernel/Monoid.scala
  kernel/src/main/scala/cats/kernel/Order.scala
  kernel/src/main/scala/cats/kernel/Semigroup.scala
  kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
  kernel/src/main/scala/cats/kernel/instances/StringInstances.scala
Labels: enhancement

#3235 Added flatMapK to FreeT
  free/src/main/scala/cats/free/FreeT.scala
Labels: enhancement
