Repository typelevel/cats, pull requests merged in 2022-10, with the labels that each got.

#4243 Added `parFlatMapN`
  project/Boilerplate.scala
  tests/shared/src/test/scala/cats/tests/ParallelSuite.scala
  tests/shared/src/test/scala/cats/tests/SyntaxSuite.scala
Labels: enhancement

#4314 Singleton monoid instances
  core/src/main/scala/cats/data/Chain.scala
  kernel/src/main/scala-2.13+/cats/kernel/instances/LazyListInstances.scala
  kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
  kernel/src/main/scala/cats/kernel/instances/QueueInstances.scala
  kernel/src/main/scala/cats/kernel/instances/SeqInstances.scala
  kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala
Labels: optimization

#4309 Avoid allocations for `Monoid` instances where possible
  core/src/main/scala/cats/data/Chain.scala
  kernel/src/main/scala-2.13+/cats/kernel/instances/LazyListInstances.scala
  kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
  kernel/src/main/scala/cats/kernel/instances/QueueInstances.scala
  kernel/src/main/scala/cats/kernel/instances/SeqInstances.scala
  kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala
Labels: optimization

#4296 Don't require `Order` for the value on `Cogen` for `SortedMap` and `NonEmptyMap`
  laws/src/main/scala/cats/laws/discipline/arbitrary.scala
Labels: bug

#4315 Recreated compat as a package object in scala_3 to make the artifact usable from scala 2
  core/src/main/scala-3/src/main/scala/cats/compat/package.scala
  mima.sbt
Labels: bug

#4287 Added `Align` instances for `Id` and `Kleisli`
  core/src/main/scala/cats/data/Kleisli.scala
  core/src/main/scala/cats/package.scala
  tests/shared/src/test/scala/cats/tests/IdSuite.scala
  tests/shared/src/test/scala/cats/tests/KleisliSuite.scala
Labels: enhancement

#4318 Include laws in published API docs
  build.sbt
Labels: documentation

#4321 Fix markdown syntax for link to `Applicative` in `OptionT`
  docs/datatypes/optiont.md
Labels: documentation

#4323 Fix obvious and straightforward warnings
  algebra-laws/shared/src/main/scala/algebra/laws/Rules.scala
  core/src/main/scala-2.13+/cats/instances/lazyList.scala
  core/src/main/scala-2.13+/cats/instances/stream.scala
  core/src/main/scala-2/src/main/scala/cats/arrow/FunctionKMacros.scala
  core/src/main/scala/cats/data/EitherT.scala
  core/src/main/scala/cats/data/Func.scala
  core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala
  core/src/main/scala/cats/data/IndexedStateT.scala
  core/src/main/scala/cats/data/Ior.scala
  core/src/main/scala/cats/data/Validated.scala
  core/src/main/scala/cats/instances/either.scala
  core/src/main/scala/cats/instances/list.scala
  core/src/main/scala/cats/instances/map.scala
  core/src/main/scala/cats/instances/queue.scala
  core/src/main/scala/cats/instances/seq.scala
  core/src/main/scala/cats/instances/sortedMap.scala
  core/src/main/scala/cats/instances/vector.scala
  kernel-laws/shared/src/main/scala/cats/kernel/laws/SerializableLaws.scala
  laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
  laws/src/main/scala/cats/laws/DeferLaws.scala
  laws/src/main/scala/cats/laws/ShortCircuitingLaws.scala
Labels: behind-the-scenes

#4326 Make string building a bit more efficient for `NonEmptySeq`
  core/src/main/scala/cats/data/NonEmptySeq.scala
Labels: optimization

#4324 Add `ApplicativeError#voidError`
  core/src/main/scala/cats/ApplicativeError.scala
  core/src/main/scala/cats/syntax/applicativeError.scala
  laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
  laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala
  laws/src/main/scala/cats/laws/discipline/ApplicativeTests.scala
  tests/shared/src/test/scala/cats/tests/SyntaxSuite.scala
Labels: enhancement
