Repository typelevel/cats, pull requests merged in 2022-07, with the labels that each got.

#4248 Added `updated` to `Traverse`
  core/src/main/scala/cats/Traverse.scala
  core/src/main/scala/cats/data/Chain.scala
  core/src/main/scala/cats/data/NonEmptyChain.scala
  core/src/main/scala/cats/data/NonEmptyList.scala
  core/src/main/scala/cats/data/NonEmptyVector.scala
  core/src/main/scala/cats/instances/StaticMethods.scala
  core/src/main/scala/cats/instances/list.scala
  core/src/main/scala/cats/instances/queue.scala
  core/src/main/scala/cats/instances/vector.scala
  laws/src/main/scala/cats/laws/TraverseLaws.scala
  tests/shared/src/test/scala/cats/tests/TraverseSuite.scala
Labels: enhancement

#4255 Add proof of inconsistency for a `Validated` Monad
  docs/datatypes/validated.md
  docs/typeclasses/parallel.md
Labels: documentation

#4264 Refactored `Chain` and `CollectiveMonoid` benchmarks
  bench/src/main/scala/cats/bench/ChainBench.scala
  bench/src/main/scala/cats/bench/CollectionMonoidBench.scala
  bench/src/main/scala/cats/bench/MapMonoidBench.scala
  build.sbt
Labels: behind-the-scenes

#4269 Mention `tupled` syntax, a Cats workhorse that deserves to be more well known
  docs/typeclasses/applicative.md
Labels: documentation

#3871 Optimise boilerplate generators, use instance constructors
  core/src/main/scala/cats/Show.scala
  kernel/src/main/scala/cats/kernel/Hash.scala
  project/AlgebraBoilerplate.scala
  project/Boilerplate.scala
  project/KernelBoiler.scala
  project/TupleBifunctorInstancesBoiler.scala
  project/TupleBitraverseInstancesBoiler.scala
  project/TupleMonadInstancesBoiler.scala
  project/TupleShowInstancesBoiler.scala
  project/TupleUnorderedFoldableInstancesBoiler.scala
Labels: optimization

#4274 Add missing `scala` modifier to code block
  docs/typeclasses/applicativemonaderror.md
Labels: documentation

#4238 Build docs on 2.13
  .github/workflows/ci.yml
  build.sbt
  docs/datatypes/writer.md
  docs/typeclasses/foldable.md
  docs/typeclasses/nonemptytraverse.md
  docs/typeclasses/reducible.md
Labels: documentation

#4275 Add `collectFirst` to the `NonEmptyCollection` interface
  core/src/main/scala/cats/data/NonEmptyCollection.scala
  core/src/main/scala/cats/data/NonEmptyList.scala
  core/src/main/scala/cats/data/NonEmptySeq.scala
  core/src/main/scala/cats/data/NonEmptyVector.scala
  tests/shared/src/test/scala/cats/tests/NonEmptyCollectionSuite.scala
Labels: enhancement
