Repository typelevel/cats, pull requests merged in 2023-05, with the labels that each got.

#4431 add `zip` for `NonEmptySeq`
  core/src/main/scala/cats/data/NonEmptySeq.scala
  tests/shared/src/test/scala/cats/tests/NonEmptySeqSuite.scala
Labels: enhancement

#4434 Add `Functor#composeBifunctor`
  core/src/main/scala/cats/Bifunctor.scala
  core/src/main/scala/cats/Composed.scala
  core/src/main/scala/cats/Functor.scala
  tests/shared/src/test/scala/cats/tests/BifunctorSuite.scala
Labels: enhancement

#4420 Add `Validated.unit`
  core/src/main/scala/cats/data/Validated.scala
Labels: enhancement

#4417 Avoid allocating an `Option` in `NonEmptyList#last`
  core/src/main/scala/cats/data/NonEmptyList.scala
Labels: optimization

#4436 Add `raiseWhen`/`raiseUnless` convenience methods to `EitherObjectOps`
  core/src/main/scala/cats/syntax/either.scala
  tests/shared/src/test/scala/cats/tests/EitherSuite.scala
Labels: enhancement

#4440 Improve `foldRight` for `Seq` instance
  core/src/main/scala/cats/instances/seq.scala
Labels: optimization

#4442 ExhaustiveCheck is a list, not a stream
  laws/src/main/scala/cats/laws/discipline/ExhaustiveCheck.scala
Labels: documentation

#4443 Fix `traverseWithIndex` => `traverseWithIndexM`
  docs/nomenclature.md
Labels: documentation

#4446 Fix typo in core's package object docs
  core/src/main/scala/cats/package.scala
Labels: documentation
