Repository typelevel/cats, pull requests merged in 2023-02, with the labels that each got.

#4390 Add `OptionT` combinators for effectful Boolean
  core/src/main/scala/cats/data/OptionT.scala
  docs/nomenclature.md
  tests/shared/src/test/scala/cats/tests/OptionTSuite.scala
Labels: enhancement

#4393 Publish alleycats docs on website
  docs/alleycats.md
  docs/directory.conf
Labels: documentation

#4398 Move `NonEmptyReducible` into its own file
  core/src/main/scala/cats/NonEmptyReducible.scala
  core/src/main/scala/cats/Reducible.scala
Labels: behind-the-scenes

#4399 Update CONTRIBUTING.md microsite information
  CONTRIBUTING.md
Labels: documentation

#4386 Improve `Chain` Documentation
  build.sbt
  docs/datatypes/chain.md
  docs/datatypes/ior.md
Labels: documentation

#4401 Add API documentation links
  docs/datatypes/const.md
  docs/datatypes/contt.md
  docs/datatypes/eithert.md
  docs/datatypes/eval.md
  docs/datatypes/freeapplicative.md
  docs/datatypes/freemonad.md
  docs/datatypes/functionk.md
  docs/datatypes/id.md
  docs/datatypes/ior.md
  docs/datatypes/iort.md
  docs/datatypes/kleisli.md
  docs/datatypes/nel.md
  docs/datatypes/nested.md
  docs/datatypes/oneand.md
  docs/datatypes/optiont.md
  docs/datatypes/state.md
  docs/datatypes/statet.md
  docs/datatypes/validated.md
  docs/datatypes/writer.md
  docs/datatypes/writert.md
  docs/typeclasses/alternative.md
  docs/typeclasses/applicative.md
  docs/typeclasses/applicativemonaderror.md
  docs/typeclasses/arrow.md
  docs/typeclasses/arrowchoice.md
  docs/typeclasses/bifoldable.md
  docs/typeclasses/bifunctor.md
  docs/typeclasses/bimonad.md
  docs/typeclasses/comonad.md
  docs/typeclasses/contravariant.md
  docs/typeclasses/contravariantmonoidal.md
  docs/typeclasses/eq.md
  docs/typeclasses/foldable.md
  docs/typeclasses/functor.md
  docs/typeclasses/invariant.md
  docs/typeclasses/invariantmonoidal.md
  docs/typeclasses/monad.md
  docs/typeclasses/monoid.md
  docs/typeclasses/monoidk.md
  docs/typeclasses/nonemptytraverse.md
  docs/typeclasses/parallel.md
  docs/typeclasses/reducible.md
  docs/typeclasses/semigroup.md
  docs/typeclasses/semigroupk.md
  docs/typeclasses/show.md
  docs/typeclasses/traverse.md
Labels: documentation
