Repository typelevel/cats, pull requests merged in 2023-07, with the labels that each got.

#4463 Making Map.unorderedTraverse stack safe
  bench/src/main/scala/cats/bench/UnorderedTraverseMapBench.scala
  core/src/main/scala/cats/instances/map.scala
  tests/shared/src/test/scala/cats/tests/MapSuite.scala
Labels: bug

#4400 Remove `Either` documentation page
  docs/datatypes/directory.conf
  docs/datatypes/either.md
  docs/datatypes/ior.md
  docs/datatypes/writert.md
  docs/faq.md
  docs/jump_start_guide.md
  docs/typeclasses/applicativemonaderror.md
Labels: documentation

#4458 Fix ambiguous `Const` instances and add missing instances
  core/src/main/scala/cats/data/Const.scala
  tests/shared/src/test/scala/cats/tests/ConstSuite.scala
Labels: enhancement

#4445 Add doctest for `IdT`
  core/src/main/scala/cats/data/IdT.scala
Labels: documentation
